### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by xat** [K15t/spark-build#1]
Nice work @SvenWalter :-)

Here are some quick thoughts that came up looking through the source:
Instead of using globals in the config.js I think it would be nicer to require this module and then
pass in an config object. Somehow like this:

``` JavaScript
var sparkBuild = require('spark-build');

var spark = sparkBuild({
    paths: [],
    karmaPort: 9876,
    moduleName: 'my-angular-project'
});
```

`spark` could then have some methods to enable certain gulp tasks (maybe you don't need all of the gulp tasks in every project):

``` JavaScript
spark.load('dev:index'); // enables the gulp 'dev:index' task
spark.load('dev:index', { ignoreCSS: true }); // hand in some config object to the task
spark.load('dev:*'); // enables all dev tasks
```

So a projects gulpfile.js would then most times basicly look somehow like this:

``` JavaScript
var sparkBuild = require('spark-build');

var spark = sparkBuild({
    paths: [],
    karmaPort: 9876,
    moduleName: 'my-angular-project'
});

spark.load('dev:*');
spark.load('dist:*');
```

**Comment by xat** [comment]
Maybe also the possibility to redefine a task would be nice. This would allow to add project specific logic (if needed):

``` JavaScript
spark.task('dev:index', function() {
// new implementation of the dev:index task
});
```

**Comment by SvenWalter** [comment]
THX ... and very good input. I updated the tasks and removed the globals. Now you can directly provide the project specific configuration to the build task by calling the corresponding function - almost the same as you suggested.
Furthermore, providing the possibility to define individually which task will be executed is also possible by defining a new task in your project specific gulp file ... which also allows to override existing task like the default task if required. In case we need a more flexible strategy then your proposal could be the right way to go using task.load.
